In [1]:
mylist = [1,2,3]

In [2]:

import numpy as np

In [3]:
arr = np.array(mylist)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.76324909, 0.11171805, 0.63116234, 0.94249172, 0.31858242])

In [17]:
np.random.rand(5,5)

array([[0.35453351, 0.25181919, 0.16189295, 0.11932858, 0.69940577],
       [0.70626791, 0.00644699, 0.73744899, 0.0985079 , 0.52586122],
       [0.57807474, 0.61773713, 0.26515107, 0.40247914, 0.63250439],
       [0.84709831, 0.82139111, 0.52283863, 0.49505188, 0.15971963],
       [0.39564017, 0.79521681, 0.8570131 , 0.20033946, 0.94847273]])

In [19]:
np.random.randn(4,4)

array([[-0.02891998,  1.5964424 ,  0.06386899, -2.03076087],
       [-2.26382754, -0.7361808 , -0.5001934 ,  0.18299449],
       [ 0.60776648, -0.42871915,  0.33260754,  2.0648529 ],
       [-0.77735526, -0.06187205,  1.08362293, -0.06036986]])

In [21]:
np.random.randint(1,100,6)

array([29, 18, 93, 60, 93, 48], dtype=int32)

In [22]:
np.random.randint(1,100,(3,3))

array([[36, 67, 62],
       [63, 90, 25],
       [72,  3, 83]], dtype=int32)

In [23]:
arr = np.arange(25)

In [24]:
ranarr = np.random.randint(0,50,10)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr

array([31, 31, 14, 22,  6, 15, 13,  3, 32, 42], dtype=int32)

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr

array([31, 31, 14, 22,  6, 15, 13,  3, 32, 42], dtype=int32)

In [29]:
ranarr.max()

np.int32(42)

In [30]:
ranarr.min()

np.int32(3)

In [31]:
ranarr.argmax()

np.int64(9)

In [32]:
ranarr.argmin()

np.int64(7)

In [33]:
arr.shape

(25,)

In [34]:
arr = arr.reshape(5,5)

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int64')

In [39]:
from numpy.random import randint

In [40]:
randint(2,10)

2